/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "media.h"

int *
add_5_svc(numbers *argp, struct svc_req *rqstp)
{
	static int result;


	
	result = ((argp->nota1* 2) + (argp->nota2 * 3))/5;

	if(result >= 60){
		
		printf("O aluno foi aprovado com a media: %d\n", result);
	
	}
	
	if(result < 60){
			
		printf("O aluno foi para a prova final com a media: %d\n", result);
	
	}
	
	

	return &result;
}
