/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "media.h"

bool_t
xdr_numbers (XDR *xdrs, numbers *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->nota1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->nota2))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->final))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->media))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->nota1);
			IXDR_PUT_LONG(buf, objp->nota2);
			IXDR_PUT_LONG(buf, objp->final);
			IXDR_PUT_LONG(buf, objp->media);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->nota1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->nota2))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->final))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->media))
				 return FALSE;
		} else {
			objp->nota1 = IXDR_GET_LONG(buf);
			objp->nota2 = IXDR_GET_LONG(buf);
			objp->final = IXDR_GET_LONG(buf);
			objp->media = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->nota1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nota2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->final))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->media))
		 return FALSE;
	return TRUE;
}
